version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ../front-end
      dockerfile: ../docker/front-end/Dockerfile.${ENVIRONMENT:-dev}
    expose:
      - "3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend

  backend:
    build:
      context: ../back-end
      dockerfile: ../docker/back-end/Dockerfile.${ENVIRONMENT:-dev}
    expose:
      - "5000"
    volumes:
      - ../back-end:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/myapp_${ENVIRONMENT:-dev}
      - NODE_ENV=${ENVIRONMENT:-development}
    depends_on:
      - db

  db:
    image: postgres:13
    expose:
      - "5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_${ENVIRONMENT:-dev}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: