version: '3.8'

services:

  backend:
    build:
      context: ../back-end
      dockerfile: ../docker/back-end/Dockerfile.${ENVIRONMENT:-dev}
    expose:
      - "5000"
    volumes:
      - ../back-end:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/myapp_${ENVIRONMENT:-dev}
      - NODE_ENV=${ENVIRONMENT:-development}
    depends_on:
      - db

  db:
    image: postgres:13
    expose:
      - "5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_${ENVIRONMENT:-dev}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: