name: geojot-dev

version: '3.8'

services:
  # TODO: add reverse proxy service

  # TODO: add front-end service 

    backend:
      container_name: backend
      build:
        context: ../back-end
        dockerfile: ../docker/back-end/Dockerfile.dev
      env_file: ../envs/back-end/.env.dev
      ports: 
        - "${BACKEND_HPORT}:5000"
      volumes:
        - ../back-end:/back-end
        - /back-end/node_modules 
      depends_on:
        - db 


    db:
      container_name: db
      image: postgres
      ports: 
        - "${DB_HPORT}:5432"
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - db-data:/var/lib/postgresql/data  
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s

volumes:
  db-data:  
networks:
  geojot-network-dev: 