FROM node:22

# Enable corepack for pnpm support
RUN corepack enable

WORKDIR /back-end

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# COPY prisma ./prisma/

# Install dependencies
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Command to run migrations and start the application in development mode
CMD ["/bin/sh", "-c", "pnpm run prisma:dev:start && pnpm run start:dev"]